---
- name: repository install
  yum: name={{ rpm }} state=installed

- name: nginx installed
  yum: name=nginx state=installed

- name: set config
  when: nginx_config is defined
  template: src={{ nginx_config }} dest=/etc/nginx/nginx.conf owner=root mode=644

- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes

- name: set access.log permission
  file: path=/var/log/nginx/access.log mode=0755

- name: set error.log permission
  file: path=/var/log/nginx/error.log mode=0755


