src: /usr/local/bin
version: kibana-4.0.1-linux-x64
tar_gz: https://download.elasticsearch.org/kibana/kibana/{{ version }}.tar.gz
kibana_elasticsearch_ip: localhost
kibana_supervisor_program_name: kibana4
kibana_user: root
supervisor_config:
  - { program: "{{ kibana_supervisor_program_name }}", option: command, value: "{{ src }}/{{ version }}/bin/kibana"}
  - { program: "{{ kibana_supervisor_program_name }}", option: autostart, value: true }
  - { program: "{{ kibana_supervisor_program_name }}", option: autorestart, value: true }
  - { program: "{{ kibana_supervisor_program_name }}", option: log_stdout, value: true }
  - { program: "{{ kibana_supervisor_program_name }}", option: log_stderr, value: true }
  - { program: "{{ kibana_supervisor_program_name }}", option: stopsignal, value: QUIT }
  - { program: "{{ kibana_supervisor_program_name }}", option: logfile, value: "/var/log/supervisor/{{ kibana_supervisor_program_name }}.log" }
