kibana_version: kibana-4.0.2-linux-x64
kibana:
  src: /usr/local/bin
  tar_gz: https://download.elasticsearch.org/kibana/kibana/{{ kibana_version }}.tar.gz
  elasticsearch_ip: "{{ groups.elasticsearch_master.0 | default('localhost') }}"
  user: root
  supervisor_program: kibana4

kibana_supervisor:
  config:
    - { program: "{{ kibana.supervisor_program }}", option: command, value: "{{ kibana.src }}/{{ kibana_version }}/bin/kibana"}
    - { program: "{{ kibana.supervisor_program }}", option: autostart, value: true }
    - { program: "{{ kibana.supervisor_program }}", option: autorestart, value: true }
    - { program: "{{ kibana.supervisor_program }}", option: log_stdout, value: true }
    - { program: "{{ kibana.supervisor_program }}", option: log_stderr, value: true }
    - { program: "{{ kibana.supervisor_program }}", option: stopsignal, value: QUIT }
    - { program: "{{ kibana.supervisor_program }}", option: logfile, value: "/var/log/supervisor/{{ kibana.supervisor_program }}.log" }
