- name: install
  yum: name=supervisor state=installed enablerepo=epel

- name: set init file
  template: src=init.j2 dest=/etc/init/supervisord.conf owner=root mode=0755

- name: run
  service: name=supervisord state=running

