- name: openjdk
  yum: name={{ openjdk }} state=installed

- name: install python setup tools
  yum: name=python-setuptools state=installed

- name: install elasticsearch-curator
  shell: easy_install {{ item }}
  with_items:
    - six==1.4
    - pbr
    - elasticsearch-curator

- name: elasticsearch
  yum: name={{ rpm }} state=present

- name: check exist plugins
  stat: path=/usr/share/elasticsearch/plugins/{{ item.key }}
  with_dict: elasticsearch_plugins
  register: exist_plugins

- name: "elasticsearch plugin install"
  when: item.1.stat.exists == false
  command: /usr/share/elasticsearch/bin/plugin --install {{ elasticsearch_plugins[item.0].repo }}
  with_together:
    - elasticsearch_plugins
    - exist_plugins.results

- name: "elasticsearch config set"
  template: src={{ elasticsearch_node_type }}.j2 dest=/etc/elasticsearch/elasticsearch.yml  owner=root mode=755
  notify: restart elasticsearch

- name: set heap size
  replace: >
    dest=/etc/sysconfig/elasticsearch
    regexp='#ES_HEAP_SIZE=2g'
    replace='ES_HEAP_SIZE={{ elasticsearch_heap_size }}'
    backup=yes

- name: start elasticsearch
  service: name=elasticsearch state=running enabled=yes

- name: set cron for curator
  when: ansible_eth1.ipv4.address == groups.elasticsearch_master.0
  cron: >
    name="curator delete indices {{ item.key }}"
    minute="{{ item.value.exec_minute }}"
    hour="{{ item.value.exec_hour }}"
    state="{{ item.value.state }}"
    job="/usr/bin/curator --host {{ groups.elasticsearch_master.0 }} delete indices --prefix {{ item.key }} --older-than {{ item.value.available_days }} --time-unit days --timestring \%Y-\%m-\%d"
  with_dict: curator_indices
