- name: openjdk
  yum: name={{ openjdk }} state=installed

- name: elasticsearch
  yum: name={{ rpm }} state=present

- name: check exist plugins
  stat: path=/usr/share/elasticsearch/plugins/{{ item.key }}
  with_dict: elasticsearch_plugins
  register: exist_plugins

- name: "elasticsearch plugin install"
  when: item.1.stat.exists == false
  command: /usr/share/elasticsearch/bin/plugin --install {{ elasticsearch_plugins[item.0].repo }}
  with_together:
    - elasticsearch_plugins
    - exist_plugins.results

- name: "elasticsearch config set"
  template: src={{ elasticsearch_node_type }}.j2 dest=/etc/elasticsearch/elasticsearch.yml  owner=root mode=755
  notify: restart elasticsearch

- name: start elasticsearch
  service: name=elasticsearch state=running enabled=yes

