elasticsearch_environment: 'ec2'
elasticsearch_heap_size: 8g
elasticsearch_config_aws:
  region: "ap-southeast-1"
  availability_zones: "ap-southeast-1a,ap-southeast-1b"
  security_group: "elasticsearch"
elasticsearch_plugins:
  cloud-aws:
    repo: elasticsearch/elasticsearch-cloud-aws/2.5.0

curator_available_days: 60
curator_exec_minute: 30
curator_exec_hour: 3
curator_indices:
  - balancer
  - backend
  - daemon
  - monitor
